//  Generates sample records for the AWS S3 File Utilities Lightning components.
//
//  Copyright (c) 2022, salesforce.com, inc.
//  All rights reserved.
//  SPDX-License-Identifier: BSD-3-Clause
//  For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
//
//  Contact: john.meyer@salesforce.com

insert new Contact(FirstName = 'John', LastName = 'Meyer');